services:
  - type: web
    name: ai-video-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: frontend
    env: node
    envVersion: "18"
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port 3000
    autoDeploy: true
    workingDirectory: frontend
    plan: free
