services:
  - type: web
    name: backend
    env: python
    envVersion: "3"
    buildCommand: |
      cd backend && python -m pip install --upgrade pip
      cd backend && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    workingDirectory: backend
    plan: free

  - type: web
    name: frontend
    env: node
    envVersion: "18"
    buildCommand: |
      cd frontend && npm install
      cd frontend && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port 3000
    autoDeploy: true
    workingDirectory: frontend
    plan: free
